function score = SSD(frame1,frame2)
    score = sum(sum([dist2(squeeze(frame1(:,:,1)),squeeze(frame2(:,:,1))),...
                     dist2(squeeze(frame1(:,:,2)),squeeze(frame2(:,:,2))),...
                     dist2(squeeze(frame1(:,:,3)),squeeze(frame2(:,:,3)))]));
end